services:
  - type: web
    name: joj-backend
    runtime: docker
    dockerContext: modele_AI
    dockerfilePath: modele_AI/Dockerfile
    plan: starter
    region: frankfurt
    envVars:
      - key: PORT
        value: 8000
